import type { Metadata } from "next";
import { Elms_Sans } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "next-themes";
import { Toaster } from "@/components/ui/sonner"

const elmsSans = Elms_Sans({
  variable: "--font-elms-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Category 7 Internet Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <>
        <html lang="en" suppressHydrationWarning className={`$ ${elmsSans.variable} antialiased`}>
        <head />
        <body>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        <Toaster richColors={true}/>
        </body>
        </html>
      </>
  );
}
